### ISSUE TITLE
Keyboard Layout 

### ISSUE THREAD

**Issue by ThavaNix** [arcolinux/arcolinux-config-budgie#1]
the extension of gnome creates problem for the keyboard layout on budgie.
I use the French keyboard but by default after installation it takes the Belgian keyboard because of the extension of gnome

**Comment by arcolinuxz** [comment]
we know
no solution yet
just switch top right to your keyboard
or add it
it is hidden in the dconf 
but so are all your keyboard shortcuts

it is a pickle

**Comment by ThavaNix** [comment]
in this case delete the extension.

**Comment by arcolinuxz** [comment]
I was never thinking of an extension.... this is just part of gnome.

Are you talking about something else...
The dropdown to choose all the keyboards is NOT an extension.

That is what we are talking about right.
